apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    app.kubernetes.io/name: demostrate-demo
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: 
    - wget -c https://github.com/ekristen/aws-nuke/releases/download/$AWS_NUKE_VERSION/aws-nuke-$AWS_NUKE_VERSION-linux-arm64.tar.gz -O - | tar -xz
    - wget https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_arm64 && mv yq_linux_arm64 /usr/bin/yq && chmod +x /usr/bin/yq
    - echo "Downloading nuke config from S3"
