apiVersion: apps/v1
kind: pod
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
    # Liveness: Riavvia il container se /healthz non risponde con 200-399
  livenessProbe:
    httpGet:
      path: /healthz
      port: 80
    initialDelaySeconds: 3 # Aspetta 3 secondi prima del primo controllo [6]
    periodSeconds: 3       # Esegui il controllo ogni 3 secondi [7]

    # Readiness: Non inviare traffico finché /ready non risponde
  readinessProbe:
    httpGet:
      path: /ready
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
