apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: linkwarden
      containers:
      - name: linkwarden
        image: ghcr.io/linkwarden/linkwarden:latest
        env:
          - name: DATABASE_URL
            value: "/subscriptions/8da69e6f-64ad-471e-b21a-1e499cd9d360/resourceGroups/aks/providers/Microsoft.DBforPostgreSQL/flexibleServers/prova"
          - name: NEXTAUTH_SECRET
            value: "something_very_random"
          - name: NEXTAUTH_URL
            value: "http://localhost:3000" # Change to your domain later
        ports:
        - containerPort: 3000
        SyncPolicy:
          syncOptions:
          - CreateNamespace=true
---
apiVersion: v1
kind: Service
metadata:
  name: linkwarden-service
spec:
  type: LoadBalancer # Or NodePort if you're on a local cluster like Minikube
  selector:
    app: linkwarden
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
