apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      containers:
      - name: linkwarden
        image: ghcr.io/linkwarden/linkwarden:latest
        env:
          - name: DATABASE_URL
            value: "prova.postgres.database.azure.com"
          - name: NEXTAUTH_SECRET
            value: "something_very_random"
          - name: NEXTAUTH_URL
            value: "http://localhost:3000" # Change to your domain later
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: linkwarden-service
spec:
  type: LoadBalancer # Or NodePort if you're on a local cluster like Minikube
  selector:
    app: linkwarden
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
